[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "thomson-profile-regularization"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "jax",
    "scipy",
    "matplotlib",
    "numpy",
    "h5py",
    "interpax",
    "optax",
    "tqdm",
    "tomli >= 2.0; python_version < '3.11'",
]

[project.scripts]
thomson-fit = "thomson_fit:main"
thomson-forward = "thomson_forward:main"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools]
py-modules = ["thomson_fit", "thomson_forward"]

[tool.setuptools.package-data]
ThomsonScattering = ["dispersion_tables.h5"]
